name: Build Docker

on:
  push:
    branches: ['master']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.4
      - run: ko publish -B ./
        env:
          KO_DOCKER_REPO: ghcr.io/dearrude
