name: Lint and format

on:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.org'
  push:
    paths-ignore:
    - '**.md'
    - '**.org'

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: nixbuild/nix-quick-install-action@v16
      with:
        nix_conf: experimental-features = nix-command flakes
    - uses: actions/checkout@v3
    - name: Check format
      run: nix run nixpkgs#golangci-lint -- run

  nixfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: nixbuild/nix-quick-install-action@v16
      with:
        nix_conf: experimental-features = nix-command flakes
    - uses: actions/checkout@v3
    - name: Check format
      run: nix run nixpkgs#nixfmt -- --check *.nix
